{{- if or .Values.apiKey .Values.readOnlyApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qdrant.fullname" . }}-apikey
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
{{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
data:
{{ include "qdrant.secret" . | indent 2}}
{{- end }}
