apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qdrant.fullname" . }}
{{- if or .Values.serviceAccount.annotations .Values.additionalAnnotations }}
  annotations:
{{- with .Values.additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}