{{- if .Values.headlessService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qdrant.fullname" . }}-headless
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
    {{- include "qdrant.additionalLabels" . | nindent 4 }}
    app.kubernetes.io/component: cluster-discovery
{{- $additionalLabels := .Values.service.additionalLabels }}
{{- if not (kindIs "invalid" .Values.headlessService.additionalLabels) }}
  {{- $additionalLabels = .Values.headlessService.additionalLabels }}
{{- end }}
{{- with $additionalLabels }}
{{- toYaml . | nindent 4 }}
{{- end }}
{{- $annotations := .Values.service.annotations }}
{{- if not (kindIs "invalid" .Values.headlessService.annotations) }}
  {{- $annotations = .Values.headlessService.annotations }}
{{- end }}
{{- if or $annotations .Values.additionalAnnotations }}
  annotations:
{{- with .Values.additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with $annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
      {{- if .appProtocol }}
      appProtocol: {{ .appProtocol }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "qdrant.selectorLabels" . | nindent 4 }}
{{- end }}